# Generated by Django 4.1.3 on 2024-01-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddyapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('context_data', models.TextField()),
            ],
        ),
    ]
