# Generated by Django 4.1.3 on 2024-01-24 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddyapi', '0002_conversationcontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_origin', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studybuddyapi.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studybuddyapi.user'),
            preserve_default=False,
        ),
    ]
