# Generated by Django 4.1.3 on 2024-01-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddyapi', '0003_user_conversationcontext_user_id_topic_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='country_of_origin',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
