# Generated by Django 4.1.3 on 2024-01-25 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddyapi', '0005_remove_topic_user_id_delete_conversationcontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studybuddyapi.user'),
            preserve_default=False,
        ),
    ]
