# Generated by Django 4.1.3 on 2024-01-25 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddyapi', '0006_topic_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='user_id',
        ),
    ]
